### PR TITLE
Add tips for yaf route match

### PR DESCRIPTION
**Pull request by netroby**
Signed-off-by: huzhifeng <huzhifeng@douyu.tv>

### CODE REVIEW

**Comment by netroby** [comment]
ping @laruence

**Comment by laruence** [comment]
应该说数组的顺序, 不应该说"最底下的".....

**Comment by netroby** [comment]
Fixed typo as you suggest.

**Comment by netroby** [comment]
ping @laruence 
Hello, any other problem? and can this got merged?

**Pull request merged**
